"""empty message

Revision ID: 0d6cf5601a3b
Revises: d160791cb20a
Create Date: 2024-07-09 16:23:47.145001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6cf5601a3b'
down_revision = 'd160791cb20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('en_passant', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.drop_column('en_passant')

    # ### end Alembic commands ###
