"""empty message

Revision ID: 4e2a96a34ff0
Revises: ccbc897d6faa
Create Date: 2024-07-12 11:07:56.002808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2a96a34ff0'
down_revision = 'ccbc897d6faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.alter_column('position_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.alter_column('position_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
