"""empty message

Revision ID: 84546f6147a3
Revises: 38bd84c7fd36
Create Date: 2024-07-12 00:22:55.442067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84546f6147a3'
down_revision = '38bd84c7fd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.drop_column('value')

    # ### end Alembic commands ###
