"""empty message

Revision ID: ccbc897d6faa
Revises: 84546f6147a3
Create Date: 2024-07-12 11:05:28.753093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccbc897d6faa'
down_revision = '84546f6147a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.alter_column('position_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.alter_column('position_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
